services:
  mysql:
    image: mysql:8
    container_name: mysql-sequelize
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expressdb
      MYSQL_USER: expressuser
      MYSQL_PASSWORD: expresspass
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
